
import {
  FileText,
  PieChart,
  ShieldCheck,
  Zap,
  Users,
  DollarSign,
  Calendar,
  Search,
  Filter,
  Shield,
  CheckCircle,
  File,
  Folder,
  MessageSquare,
  AlertTriangle,
  Headset,
  TrendingUp,
  Globe,
  GraduationCap,
  Book,
  BarChart2,
  UserCheck,
  PackageCheck,
  ThumbsUp,
  EyeOff,
  Package,
  Clock,
  CheckSquare,
  UserPlus,
  BarChart,
  Settings,
  Workflow,
  AreaChart,
  Pencil,
  Briefcase,
  Timer,
  Share2,
  GitMerge,
  Database
} from "lucide-react";

export const useCases = [
  {
    id: 1,
    name: "Client Document Analyzer",
    description: "Automatically extracts and categorizes data from client documents",
    category: "data-management",
    serviceLines: ["TAX", "ASR"],
    icon: FileText,
    priority: "high",
    phase: "Phase 1",
    complexity: "Medium",
    crossServiceValue: "High",
    keyBenefit: "60% reduction in document processing time"
  },
  {
    id: 2,
    name: "Regulatory Compliance Monitor",
    description: "Tracks and alerts on compliance requirements and deadlines",
    category: "compliance",
    serviceLines: ["TAX", "ASR", "IFS"],
    icon: ShieldCheck,
    priority: "high",
    phase: "Phase 1",
    complexity: "High",
    crossServiceValue: "High",
    keyBenefit: "90% decrease in compliance violations"
  },
  {
    id: 3,
    name: "Client Onboarding Assistant",
    description: "Streamlines client intake process and data collection",
    category: "client-interaction",
    serviceLines: ["DEALS", "IFS"],
    icon: UserPlus,
    priority: "high",
    phase: "Phase 1",
    complexity: "Low",
    crossServiceValue: "Medium",
    keyBenefit: "45% faster client onboarding"
  },
  {
    id: 4,
    name: "Financial Data Analyzer",
    description: "Identifies trends and anomalies in financial statements",
    category: "financial",
    serviceLines: ["ASR", "DEALS"],
    icon: BarChart,
    priority: "medium",
    phase: "Phase 2",
    complexity: "High",
    crossServiceValue: "Medium",
    keyBenefit: "30% improvement in financial insight accuracy"
  },
  {
    id: 5,
    name: "Process Automation Assistant",
    description: "Automates routine workflows and approval processes",
    category: "automation",
    serviceLines: ["TAX", "ASR", "DEALS", "IFS"],
    icon: Settings,
    priority: "medium",
    phase: "Phase 2",
    complexity: "Medium",
    crossServiceValue: "High",
    keyBenefit: "75% reduction in manual processing time"
  },
  {
    id: 6,
    name: "Training Content Generator",
    description: "Creates personalized learning materials for staff",
    category: "project-management",
    serviceLines: ["TAX", "ASR", "DEALS", "IFS"],
    icon: GraduationCap,
    priority: "strategic",
    phase: "Phase 3",
    complexity: "Medium",
    crossServiceValue: "High",
    keyBenefit: "40% increase in knowledge retention"
  },
  {
    id: 7,
    name: "Market Research Digest",
    description: "Summarizes industry trends and competitor activities",
    category: "data-management",
    serviceLines: ["DEALS", "IFS"],
    icon: Globe,
    priority: "medium",
    phase: "Phase 2",
    complexity: "Medium",
    crossServiceValue: "Medium",
    keyBenefit: "25% improved market intelligence"
  },
  {
    id: 8,
    name: "Client Feedback Analyzer",
    description: "Analyzes sentiment and identifies improvement areas",
    category: "client-interaction",
    serviceLines: ["TAX", "ASR", "DEALS", "IFS"],
    icon: MessageSquare,
    priority: "medium",
    phase: "Phase 2",
    complexity: "Low",
    crossServiceValue: "High",
    keyBenefit: "35% increase in client satisfaction scores"
  },
  {
    id: 9,
    name: "Risk Assessment Tool",
    description: "Evaluates and quantifies project and client risks",
    category: "compliance",
    serviceLines: ["DEALS", "IFS"],
    icon: AlertTriangle,
    priority: "high",
    phase: "Phase 1",
    complexity: "High",
    crossServiceValue: "Medium",
    keyBenefit: "50% reduction in unforeseen project risks"
  },
  {
    id: 10,
    name: "Client Support Agent",
    description: "Provides 24/7 automated responses to common client inquiries",
    category: "client-interaction",
    serviceLines: ["TAX", "ASR"],
    icon: Headset,
    priority: "medium",
    phase: "Phase 2",
    complexity: "Medium",
    crossServiceValue: "Low",
    keyBenefit: "80% of basic inquiries resolved without staff"
  },
  {
    id: 11,
    name: "Revenue Forecasting Model",
    description: "Predicts future revenue based on historical data and trends",
    category: "financial",
    serviceLines: ["DEALS"],
    icon: TrendingUp,
    priority: "strategic",
    phase: "Phase 3",
    complexity: "High",
    crossServiceValue: "Medium",
    keyBenefit: "20% improvement in forecast accuracy"
  },
  {
    id: 12,
    name: "Knowledge Base Assistant",
    description: "Provides instant access to organizational knowledge",
    category: "project-management",
    serviceLines: ["TAX", "ASR", "DEALS", "IFS"],
    icon: Book,
    priority: "high",
    phase: "Phase 1",
    complexity: "Medium",
    crossServiceValue: "High",
    keyBenefit: "65% reduction in time spent searching for information"
  },
  {
    id: 13,
    name: "Tax Planning Optimizer",
    description: "Analyzes tax scenarios to identify optimal strategies",
    category: "financial",
    serviceLines: ["TAX"],
    icon: DollarSign,
    priority: "high",
    phase: "Phase 1",
    complexity: "High",
    crossServiceValue: "Medium",
    keyBenefit: "15% average tax savings identified"
  },
  {
    id: 14,
    name: "Data Quality Monitor",
    description: "Continuously checks data integrity and identifies issues",
    category: "data-management",
    serviceLines: ["ASR", "IFS"],
    icon: Database,
    priority: "medium",
    phase: "Phase 2",
    complexity: "Medium",
    crossServiceValue: "High",
    keyBenefit: "85% reduction in data quality issues"
  },
  {
    id: 15,
    name: "Meeting Summarizer",
    description: "Automatically creates concise summaries of client meetings",
    category: "client-interaction",
    serviceLines: ["TAX", "ASR", "DEALS", "IFS"],
    icon: FileText,
    priority: "medium",
    phase: "Phase 2",
    complexity: "Low",
    crossServiceValue: "High",
    keyBenefit: "70% reduction in note-taking time"
  },
  {
    id: 16,
    name: "Contract Analysis Tool",
    description: "Extracts key terms and flags potential issues in contracts",
    category: "compliance",
    serviceLines: ["DEALS", "IFS"],
    icon: File,
    priority: "high",
    phase: "Phase 1",
    complexity: "High",
    crossServiceValue: "Medium",
    keyBenefit: "55% faster contract review process"
  },
  {
    id: 17,
    name: "Project Resource Allocator",
    description: "Optimizes staff allocation based on skills and availability",
    category: "automation",
    serviceLines: ["TAX", "ASR", "DEALS", "IFS"],
    icon: Users,
    priority: "strategic",
    phase: "Phase 3",
    complexity: "High",
    crossServiceValue: "High",
    keyBenefit: "25% improvement in resource utilization"
  },
  {
    id: 18,
    name: "Industry Compliance Tracker",
    description: "Monitors industry-specific regulatory changes",
    category: "compliance",
    serviceLines: ["TAX", "ASR", "IFS"],
    icon: Shield,
    priority: "medium",
    phase: "Phase 2",
    complexity: "Medium",
    crossServiceValue: "Medium",
    keyBenefit: "100% compliance with regulatory updates"
  },
  {
    id: 19,
    name: "Client Portfolio Analyzer",
    description: "Provides insights on client portfolios and recommends opportunities",
    category: "financial",
    serviceLines: ["DEALS", "IFS"],
    icon: PieChart,
    priority: "strategic",
    phase: "Phase 3",
    complexity: "High",
    crossServiceValue: "Medium",
    keyBenefit: "30% increase in cross-selling opportunities identified"
  },
  {
    id: 20,
    name: "Knowledge Sharing Platform",
    description: "Facilitates organization-wide expertise sharing and collaboration",
    category: "project-management",
    serviceLines: ["TAX", "ASR", "DEALS", "IFS"],
    icon: Share2,
    priority: "strategic",
    phase: "Phase 3",
    complexity: "Medium",
    crossServiceValue: "High",
    keyBenefit: "40% increase in internal knowledge sharing"
  }
];
